pages:
  image: node:lts-buster
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install --frozen-lockfile
    - pnpm build --configDeploy $CI_PAGES_URL --configName $CI_PROJECT_NAME
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
